# Generated by Django 4.1.4 on 2023-01-09 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mayflower', '0009_cntdb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='icedb',
            new_name='cakedb',
        ),
        migrations.RenameField(
            model_name='cakedb',
            old_name='Icecreamname',
            new_name='Cakename',
        ),
    ]
